/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_EMC_01 (coord F3), flexio_i2c_SDA */
#define BOARD_INITPINS_flexio_i2c_SDA_PERIPHERAL                         FLEXIO1   /*!< Device name: FLEXIO1 */
#define BOARD_INITPINS_flexio_i2c_SDA_SIGNAL                                  IO   /*!< FLEXIO1 signal: IO */
#define BOARD_INITPINS_flexio_i2c_SDA_CHANNEL                                 1U   /*!< FLEXIO1 IO channel: 01 */

/* GPIO_EMC_02 (coord F4), flexio_i2c_SCL */
#define BOARD_INITPINS_flexio_i2c_SCL_PERIPHERAL                         FLEXIO1   /*!< Device name: FLEXIO1 */
#define BOARD_INITPINS_flexio_i2c_SCL_SIGNAL                                  IO   /*!< FLEXIO1 signal: IO */
#define BOARD_INITPINS_flexio_i2c_SCL_CHANNEL                                 2U   /*!< FLEXIO1 IO channel: 02 */

/* GPIO_AD_B0_09 (coord F14), led */
#define BOARD_INITPINS_led_GPIO                                            GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_led_PORT                                            GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_led_PIN                                                9U   /*!< GPIO1 pin index: 9 */

/* GPIO_B0_00 (coord D7), qtmr1_c0 */
#define BOARD_INITPINS_qtmr1_c0_PERIPHERAL                                  TMR1   /*!< Device name: TMR1 */
#define BOARD_INITPINS_qtmr1_c0_SIGNAL                                     TIMER   /*!< TMR1 signal: TIMER */
#define BOARD_INITPINS_qtmr1_c0_CHANNEL                                       0U   /*!< TMR1 TIMER channel: 0 */

/* GPIO_B0_01 (coord E7), qtmr1_c1 */
#define BOARD_INITPINS_qtmr1_c1_PERIPHERAL                                  TMR1   /*!< Device name: TMR1 */
#define BOARD_INITPINS_qtmr1_c1_SIGNAL                                     TIMER   /*!< TMR1 signal: TIMER */
#define BOARD_INITPINS_qtmr1_c1_CHANNEL                                       1U   /*!< TMR1 TIMER channel: 1 */

/* GPIO_B0_02 (coord E8), qtmr1_c2 */
#define BOARD_INITPINS_qtmr1_c2_PERIPHERAL                                  TMR1   /*!< Device name: TMR1 */
#define BOARD_INITPINS_qtmr1_c2_SIGNAL                                     TIMER   /*!< TMR1 signal: TIMER */
#define BOARD_INITPINS_qtmr1_c2_CHANNEL                                       2U   /*!< TMR1 TIMER channel: 2 */

/* GPIO_B1_08 (coord A12), qtmr1_c3 */
#define BOARD_INITPINS_qtmr1_c3_PERIPHERAL                                  TMR1   /*!< Device name: TMR1 */
#define BOARD_INITPINS_qtmr1_c3_SIGNAL                                     TIMER   /*!< TMR1 signal: TIMER */
#define BOARD_INITPINS_qtmr1_c3_CHANNEL                                       3U   /*!< TMR1 TIMER channel: 3 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
