/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v6.0
processor: MIMXRT1064xxxxA
package_id: MIMXRT1064DVL6A
mcu_data: ksdk2_0
processor_version: 6.0.2
pin_labels:
- {pin_num: F3, pin_signal: GPIO_EMC_01, label: flexio_i2c_SDA, identifier: flexio_i2c;flexio_i2c_SDA}
- {pin_num: F4, pin_signal: GPIO_EMC_02, label: flexio_i2c_SCL, identifier: flexio_i2c_SCL}
- {pin_num: A8, pin_signal: GPIO_B0_06, label: flexio_spi_CSn, identifier: flexio_spi_;flexio_spi_CSn}
- {pin_num: A9, pin_signal: GPIO_B0_07, label: flexio_spi_SCK, identifier: flexio_spi_SCK}
- {pin_num: A10, pin_signal: GPIO_B0_11, label: flexio_spi_SDO, identifier: flexio_spi_SDO}
- {pin_num: A11, pin_signal: GPIO_B1_00, label: flexio_spi_SDI, identifier: flexio_spi_SDI}
- {pin_num: A7, pin_signal: GPIO_EMC_40, label: led_red, identifier: led_red}
- {pin_num: B12, pin_signal: GPIO_B1_07, label: led_green, identifier: led_green}
- {pin_num: C7, pin_signal: GPIO_EMC_41, label: led_blue, identifier: led_blue}
- {pin_num: B8, pin_signal: GPIO_B0_05, label: oled_dc, identifier: oled_res;oled_dc}
- {pin_num: B9, pin_signal: GPIO_B0_08, label: oled_res, identifier: oled_res}
- {pin_num: B7, pin_signal: GPIO_EMC_39, label: oled_cs, identifier: oled_cs}
- {pin_num: B6, pin_signal: GPIO_EMC_14, label: oled_dc, identifier: oled_dc}
- {pin_num: A4, pin_signal: GPIO_EMC_17, label: oled_res, identifier: oled_res}
- {pin_num: A3, pin_signal: GPIO_EMC_20, label: oled_d1, identifier: oled_d1}
- {pin_num: A2, pin_signal: GPIO_EMC_27, label: oled_d0, identifier: oled_d0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: F3, peripheral: FLEXIO1, signal: 'IO, 01', pin_signal: GPIO_EMC_01, identifier: flexio_i2c_SDA}
  - {pin_num: F4, peripheral: FLEXIO1, signal: 'IO, 02', pin_signal: GPIO_EMC_02}
  - {pin_num: A7, peripheral: GPIO3, signal: 'gpio_io, 26', pin_signal: GPIO_EMC_40, speed: MHZ_100}
  - {pin_num: B12, peripheral: GPIO2, signal: 'gpio_io, 23', pin_signal: GPIO_B1_07}
  - {pin_num: C7, peripheral: GPIO3, signal: 'gpio_io, 27', pin_signal: GPIO_EMC_41}
  - {pin_num: A2, peripheral: GPIO4, signal: 'gpio_io, 27', pin_signal: GPIO_EMC_27, pull_keeper_select: Keeper}
  - {pin_num: A3, peripheral: GPIO4, signal: 'gpio_io, 20', pin_signal: GPIO_EMC_20}
  - {pin_num: A4, peripheral: GPIO4, signal: 'gpio_io, 17', pin_signal: GPIO_EMC_17}
  - {pin_num: B6, peripheral: GPIO4, signal: 'gpio_io, 14', pin_signal: GPIO_EMC_14}
  - {pin_num: B7, peripheral: GPIO3, signal: 'gpio_io, 25', pin_signal: GPIO_EMC_39}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03U */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_07_GPIO2_IO23,           /* GPIO_B1_07 is configured as GPIO2_IO23 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_01_FLEXIO1_FLEXIO01,    /* GPIO_EMC_01 is configured as FLEXIO1_FLEXIO01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_02_FLEXIO1_FLEXIO02,    /* GPIO_EMC_02 is configured as FLEXIO1_FLEXIO02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_14_GPIO4_IO14,          /* GPIO_EMC_14 is configured as GPIO4_IO14 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_17_GPIO4_IO17,          /* GPIO_EMC_17 is configured as GPIO4_IO17 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_20_GPIO4_IO20,          /* GPIO_EMC_20 is configured as GPIO4_IO20 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_27_GPIO4_IO27,          /* GPIO_EMC_27 is configured as GPIO4_IO27 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_39_GPIO3_IO25,          /* GPIO_EMC_39 is configured as GPIO3_IO25 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_40_GPIO3_IO26,          /* GPIO_EMC_40 is configured as GPIO3_IO26 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_41_GPIO3_IO27,          /* GPIO_EMC_41 is configured as GPIO3_IO27 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_GPR->GPR27 = ((IOMUXC_GPR->GPR27 &
    (~(IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK))) /* Mask bits to zero which are setting */
      | IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL(0x00U) /* GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: 0x00U */
    );
  IOMUXC_GPR->GPR28 = ((IOMUXC_GPR->GPR28 &
    (~(IOMUXC_GPR_GPR28_GPIO_MUX3_GPIO_SEL_MASK))) /* Mask bits to zero which are setting */
      | IOMUXC_GPR_GPR28_GPIO_MUX3_GPIO_SEL(0x00U) /* GPIO3 and GPIO8 share same IO MUX function, GPIO_MUX3 selects one GPIO function: 0x00U */
    );
  IOMUXC_GPR->GPR29 = ((IOMUXC_GPR->GPR29 &
    (~(IOMUXC_GPR_GPR29_GPIO_MUX4_GPIO_SEL_MASK))) /* Mask bits to zero which are setting */
      | IOMUXC_GPR_GPR29_GPIO_MUX4_GPIO_SEL(0x00U) /* GPIO4 and GPIO9 share same IO MUX function, GPIO_MUX4 selects one GPIO function: 0x00U */
    );
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_27_GPIO4_IO27,          /* GPIO_EMC_27 PAD functional properties : */
      0x10B0U);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Down
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_40_GPIO3_IO26,          /* GPIO_EMC_40 PAD functional properties : */
      0x10B0U);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Down
                                                 Hyst. Enable Field: Hysteresis Disabled */
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
