/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v6.0
processor: MIMXRT1064xxxxA
package_id: MIMXRT1064DVL6A
mcu_data: ksdk2_0
processor_version: 6.0.2
pin_labels:
- {pin_num: F3, pin_signal: GPIO_EMC_01, label: flexio_i2c_SDA, identifier: flexio_i2c;flexio_i2c_SDA}
- {pin_num: F4, pin_signal: GPIO_EMC_02, label: flexio_i2c_SCL, identifier: flexio_i2c_SCL}
- {pin_num: A8, pin_signal: GPIO_B0_06, label: flexio_spi_CSn, identifier: flexio_spi_;flexio_spi_CSn}
- {pin_num: A9, pin_signal: GPIO_B0_07, label: flexio_spi_SCK, identifier: flexio_spi_SCK}
- {pin_num: A10, pin_signal: GPIO_B0_11, label: flexio_spi_SDO, identifier: flexio_spi_SDO}
- {pin_num: A11, pin_signal: GPIO_B1_00, label: flexio_spi_SDI, identifier: flexio_spi_SDI}
- {pin_num: A7, pin_signal: GPIO_EMC_40, label: led_red, identifier: led_red}
- {pin_num: B12, pin_signal: GPIO_B1_07, label: led_green, identifier: led_green}
- {pin_num: C7, pin_signal: GPIO_EMC_41, label: led_blue, identifier: led_blue}
- {pin_num: B8, pin_signal: GPIO_B0_05, label: oled_dc, identifier: oled_res;oled_dc}
- {pin_num: B9, pin_signal: GPIO_B0_08, label: led, identifier: oled_res;led}
- {pin_num: B7, pin_signal: GPIO_EMC_39, label: oled_cs, identifier: oled_cs}
- {pin_num: B6, pin_signal: GPIO_EMC_14, label: oled_dc, identifier: oled_dc}
- {pin_num: A4, pin_signal: GPIO_EMC_17, label: oled_res, identifier: oled_res}
- {pin_num: A3, pin_signal: GPIO_EMC_20, label: oled_d1, identifier: oled_d1}
- {pin_num: A2, pin_signal: GPIO_EMC_27, label: oled_d0, identifier: oled_d0}
- {pin_num: F14, pin_signal: GPIO_AD_B0_09, label: led, identifier: test;led}
- {pin_num: G11, pin_signal: GPIO_AD_B0_03, label: pit_0, identifier: pit_0}
- {pin_num: D7, pin_signal: GPIO_B0_00, label: qtmr1_c0, identifier: qtmr1_c0}
- {pin_num: E7, pin_signal: GPIO_B0_01, label: qtmr1_c1, identifier: qtmr1_c1}
- {pin_num: E8, pin_signal: GPIO_B0_02, label: qtmr1_c2, identifier: qtmr1_c2}
- {pin_num: A12, pin_signal: GPIO_B1_08, label: qtmr1_c3, identifier: qtmr1_c3}
- {pin_num: A13, pin_signal: GPIO_B1_09, label: oled_d0, identifier: oled_d0}
- {pin_num: B13, pin_signal: GPIO_B1_10, label: oled_d1, identifier: oled_d1}
- {pin_num: C13, pin_signal: GPIO_B1_11, label: oled_res}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: F3, peripheral: FLEXIO1, signal: 'IO, 01', pin_signal: GPIO_EMC_01, identifier: flexio_i2c_SDA}
  - {pin_num: F4, peripheral: FLEXIO1, signal: 'IO, 02', pin_signal: GPIO_EMC_02}
  - {pin_num: F14, peripheral: GPIO1, signal: 'gpio_io, 09', pin_signal: GPIO_AD_B0_09, identifier: led, direction: OUTPUT, gpio_init_state: 'false', pull_up_down_config: Pull_Up_100K_Ohm,
    pull_keeper_select: Keeper, drive_strength: R0_6}
  - {pin_num: D7, peripheral: TMR1, signal: 'TIMER, 0', pin_signal: GPIO_B0_00}
  - {pin_num: E7, peripheral: TMR1, signal: 'TIMER, 1', pin_signal: GPIO_B0_01}
  - {pin_num: E8, peripheral: TMR1, signal: 'TIMER, 2', pin_signal: GPIO_B0_02}
  - {pin_num: A12, peripheral: TMR1, signal: 'TIMER, 3', pin_signal: GPIO_B1_08}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03U */

  /* GPIO configuration of led on GPIO_AD_B0_09 (pin F14) */
  gpio_pin_config_t led_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_09 (pin F14) */
  GPIO_PinInit(GPIO1, 9U, &led_config);

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_09_GPIO1_IO09,        /* GPIO_AD_B0_09 is configured as GPIO1_IO09 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_00_QTIMER1_TIMER0,       /* GPIO_B0_00 is configured as QTIMER1_TIMER0 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_01_QTIMER1_TIMER1,       /* GPIO_B0_01 is configured as QTIMER1_TIMER1 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_02_QTIMER1_TIMER2,       /* GPIO_B0_02 is configured as QTIMER1_TIMER2 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_08_QTIMER1_TIMER3,       /* GPIO_B1_08 is configured as QTIMER1_TIMER3 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_01_FLEXIO1_FLEXIO01,    /* GPIO_EMC_01 is configured as FLEXIO1_FLEXIO01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_02_FLEXIO1_FLEXIO02,    /* GPIO_EMC_02 is configured as FLEXIO1_FLEXIO02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_GPR->GPR26 = ((IOMUXC_GPR->GPR26 &
    (~(IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK))) /* Mask bits to zero which are setting */
      | IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL(0x00U) /* GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: 0x00U */
    );
  IOMUXC_GPR->GPR6 = ((IOMUXC_GPR->GPR6 &
    (~(IOMUXC_GPR_GPR6_QTIMER1_TRM0_INPUT_SEL_MASK | IOMUXC_GPR_GPR6_QTIMER1_TRM1_INPUT_SEL_MASK | IOMUXC_GPR_GPR6_QTIMER1_TRM2_INPUT_SEL_MASK | IOMUXC_GPR_GPR6_QTIMER1_TRM3_INPUT_SEL_MASK))) /* Mask bits to zero which are setting */
      | IOMUXC_GPR_GPR6_QTIMER1_TRM0_INPUT_SEL(0x00U) /* QTIMER1 TMR0 input select: input from IOMUX */
      | IOMUXC_GPR_GPR6_QTIMER1_TRM1_INPUT_SEL(0x00U) /* QTIMER1 TMR1 input select: input from IOMUX */
      | IOMUXC_GPR_GPR6_QTIMER1_TRM2_INPUT_SEL(0x00U) /* QTIMER1 TMR2 input select: input from IOMUX */
      | IOMUXC_GPR_GPR6_QTIMER1_TRM3_INPUT_SEL(0x00U) /* QTIMER1 TMR3 input select: input from IOMUX */
    );
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_B0_09_GPIO1_IO09,        /* GPIO_AD_B0_09 PAD functional properties : */
      0x90B0U);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
